#!/bin/bash

count=0					#stores number of faulty files

not_ok=`tput setaf 1`	#texcolor for faulty files
ok=`tput setaf 2`		#texcolor non faulty files
reset=`tput sgr0`

for file in $(git diff --cached --name-only --diff-filter=ACM | grep -e '\.php$')
do
	if 	php -l ${file}
	then
		echo "${ok}$file ok${reset}"
	else
		echo -e "${not_ok}$file not ok${reset}\n" #if parse errors detected, count
		count+=1
	fi
done
if [[ $count -gt 0 ]]	#if count of faulty files > 0, exit code 1
then 
	exit 1
else
	exit 0
fi